version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin

archives:
  - formats: [tar.xz]

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    format_overrides:
      - goos: windows
        formats: [zip]

    files: ["LICENSE*"]

changelog:
  sort: asc

  filters:
    exclude:
      - "^docs:"
      - "^test:"

winget:
  - name: sens
    publisher: junapur
    license: MIT
    homepage: https://github.com/junapur/sens
    short_description: Convert mouse sensitivity between games via CLI.

    tags:
      - rust
      - cli

    repository:
      owner: junapur
      name: winget-pkgs
      branch: "{{ .ProjectName }}-{{.Version}}"

      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
