name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

assignees:
  - junapur

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! :)

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: My computer exploded when I ran the program. I expected it not to do that.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce this bug.
      placeholder: |
        1. Run command 'example-cli --flag value'
        2. Observe unexpected behavior/error
        3. Expected: ... but got: ...
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: Please confirm the following before submitting your bug report.
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
